# Generated by Django 5.1.1 on 2024-09-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
